### ISSUE TITLE
Regarding the results reported in Table 1 of your MICCAI paper

### ISSUE THREAD

**Issue by shinkyo0513** [gunnerwang/MTL-VF-and-IMTL-AGF#1]
Hi Tianyu,

I am wondering how you get the results reported in Table 1 of your MICCAI 2020 paper.
In section 3.1, it is mentioned that 'both frameworks are trained for 100 epochs ... '. 
So the results reported in the paper is those of the last (100th) epoch or the best results among all the 100 epochs?

Thank you in advance.

**Comment by gunnerwang** [comment]
Hi Zhenqiang,

The results are reported under the cross validation schemes LOSO and LOUO, which are the standard forms for JIGSAWS dataset. The model is trained on training folds and tested on validation fold. The average performance is recorded.

Hope that helps.

Best,
Tianyu Wang

----------------------------------------------------
Tianyu Wang (王天予) 
UM-SJTU Joint Institute (上海交大密西根学院) 
Shanghai Jiao Tong University 
Phone: 15921813393
Email: gunnerwang27@sjtu.edu.cn

在 2021年1月13日 上午11:45:45, Zhenqiang Li (notifications@github.com) 写到:

Hi Tianyu,

I am wondering how you get the results reported in Table 1 of your MICCAI 2020 paper.
In section 3.1, it is mentioned that 'both frameworks are trained for 100 epochs ... '.
So the results reported in the paper is those of the last (100th) epoch or the best results among all the 100 epochs?

Thank you in advance.

**Comment by shinkyo0513** [comment]
Hi Tianyu,

Thank you for the rapid response.
I am sorry if my question is not clear. 
I know the cross-validation was performed according to the JIGSAWS dataset's setting.

I would like to make my question clear. 
For each validation fold, which epoch does the reported Spearman's correlation numbers come from?
As my understanding, the numbers may be the best correlation on the validation fold among all 100 epochs, or just simply the correlation on the final 100th epoch. 

Thank you!

**Comment by gunnerwang** [comment]
Hi Zhenqiang,

Now I got it. The numbers reported are exactly the correlations on the several final-stage epoches.

**Comment by shinkyo0513** [comment]
Thank you! So rapid!

But what do you mean by the 'several final-stage epochs'?
Does it mean the correlations on the final 100th epoch of several validation folds?

Sorry for many questions.

**Comment by gunnerwang** [comment]
I mean on the final epochs, not necessarily the exact 100th epoch. The correlations of these epoches can be manually checked.

**Comment by shinkyo0513** [comment]
Oh, I see. 

Do you mind to share your standards of checking the correlations of these epochs?

**Comment by gunnerwang** [comment]
I think you can check by plotting the trend of correlations or MSE error to verify the convergeness.

**Comment by shinkyo0513** [comment]
Thank you! It is helpful.
